[build]
  publish = "."

[[redirects]]
  from = "https://www.sida-sulbi.co.kr/*"
  to = "https://sida-sulbi.co.kr/:splat"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
