[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false
  conditions = {Path = ["*[^/]", "!*.{html,css,js,jpg,png,svg,ico,xml,txt,json}"]}

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
